import os.path
import platform
import subprocess
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import TYPE_CHECKING, Iterable, List, Optional

from .context import GLOBALS, PROPERTIES
from .hglob import glob
from .output_directory import unique_folder_name
from .utils import (copy_file, ensure_directory, flush_json_if_changed,
                    relativize_or_hash_path)

if TYPE_CHECKING:
	from .includes import Includes


@dataclass
class ScriptSource:
	source_path: str
	destination_path: str
	transpiler: str

@dataclass
class DirectorySource(ScriptSource):
	includes: 'Includes'

###
# Project configs now should be readen before flushing, compared via
# object comparison (to drop comments, whitespace, etc.) and tsconfigs
# in projects itself should contain only specific source options.

# <project>
	# dev
		# .includes
		# header.ts
		# tsconfig.json (autogenerated)
	# launcher.ts
	# preloader.ts
	# tsconfig.json (autogenerated)

# Build directory configs will contain following structure:
# - Composite configs contains `composite: true` in directories and
# referenced directly in root file which will be used for release builds.
# - Incremental configs does NOT contains it, only `incremental: true`,
# no references, only direct file includes, directories built separately.
# * No separate reference/incremental tsconfig to include launcher.ts or
# preloader.ts, they will be included direcly via `include` property.

# <build_directory>
	# tsc (output directory + tsconfigs)
		# dev
			# composite-tsconfig.json
			# incremental-tsconfig.json
		# composite-tsconfig.json
		# incremental-tsconfig.json
	# babel (pretty same, but with babel configs)
	# sources (probably has been deprecated, concat transpiler outputs file directly)
###

class ScriptRepository:
	files: List[ScriptSource] = []
	directories: List[DirectorySource] = []

	def include_file(self, source_path: str, destination_path: str, transpiler: str):
		self.files.append(ScriptSource(source_path, destination_path, transpiler))

	def include_directory(self, includes: 'Includes', destination_path: str, transpiler: str):
		self.directories.append(DirectorySource(includes.directory, destination_path, transpiler, includes))

	def iterate_files(self, transpiler: Optional[str] = None) -> Iterable[ScriptSource]:
		for file in self.files:
			if not transpiler or transpiler == file.transpiler:
				yield file

	def iterate_directories(self, transpiler: Optional[str] = None) -> Iterable[DirectorySource]:
		for directory in self.directories:
			if not transpiler or transpiler == directory.transpiler:
				yield directory

	def iterate(self, transpiler: Optional[str] = None) -> Iterable[ScriptSource]:
		yield from self.iterate_files(transpiler)
		yield from self.iterate_directories(transpiler)

def resolve_declarations() -> List[str]:
	includes = GLOBALS.MAKE_CONFIG.get_value("declarations", ["declarations"])
	declarations = []
	for filepath in [
		GLOBALS.MAKE_CONFIG.get_path(include) for include in includes
	]:
		if not os.path.exists(filepath):
			continue
		if os.path.isdir(filepath):
			filepath = os.path.join(filepath, "**", "*.d.ts")
		declarations.extend(glob(filepath, recursive=True))

	toolchain_declarations = GLOBALS.TOOLCHAIN_CONFIG.get_relative_path("declarations")
	if not os.path.isdir(toolchain_declarations):
		from .output_directory import get_config_directory
		toolchain_declarations = os.path.join(get_config_directory(), "declarations")
	if os.path.isdir(toolchain_declarations):
		declarations.extend(glob(os.path.join(toolchain_declarations, "**", "*.d.ts"), recursive=True))

	return list(set(declarations))

class ScriptTranspiler(ABC):
	@abstractmethod
	def transpile(self, repository: ScriptRepository) -> int:
		...

class ConcatTranspiler(ScriptTranspiler):
	def transpile(self, repository: ScriptRepository) -> int:
		overall_result = 0

		for file in repository.iterate_files("concat"):
			if GLOBALS.BUILD_STORAGE.is_path_changed(file.source_path) or not os.path.isfile(file.destination_path):
				copy_file(file.source_path, file.destination_path)

		for directory in repository.iterate_directories("concat"):
			if directory.includes.compute(directory.destination_path, "javascript"):
				overall_result += directory.includes.build_source(directory.destination_path, "javascript")

		return overall_result

@dataclass
class TscBuildTarget:
	source: ScriptSource
	output_path: str
	incremental_path: str
	composite_path: str

class TscTranspiler(ScriptTranspiler):
	def __init__(self) -> None:
		super().__init__()
		self.tsc_path = GLOBALS.MAKE_CONFIG.get_build_path("script", "tsc")
		self.composite_path = os.path.join(self.tsc_path, "composite.tsconfig.json")

	def prepare_build_targets(self, repository: ScriptRepository) -> List[TscBuildTarget]:
		build_targets: List[TscBuildTarget] = []
		for source in repository.iterate("tsc"):
			if isinstance(source, DirectorySource):
				source_path = source.source_path
			else:
				source_path = os.path.dirname(source.source_path)
			relative_directory = relativize_or_hash_path(source_path, GLOBALS.MAKE_CONFIG.directory)
			output_directory = os.path.join(self.tsc_path, relative_directory)

			output_filename = unique_folder_name(source.source_path)
			incremental_tsconfig = os.path.join(output_directory, f"{output_filename}.tsconfig.json")
			composite_tsconfig = os.path.join(output_directory, f"{output_filename}.composite.tsconfig.json")
			output_path = os.path.join(output_directory, f"{output_filename}.js")

			build_targets.append(TscBuildTarget(source, output_path, incremental_tsconfig, composite_tsconfig))
		return build_targets

	def create_tsconfig_contents(self, include: List[str], exclude: Optional[List[str]] = None, **options) -> dict:
		template = {
			"compilerOptions": {
				# TypeScript Compiler 6+ Changes
				"strict": False,
				"ignoreDeprecations": "6.0",
				# Overrideable configurations and internal options
				**GLOBALS.TSCONFIG_TOOLCHAIN,
				**options
			},
			"exclude": [
				"dom",
				"dom.iterable",
				"es2015.iterable",
				"scripthost",
				"webworker",
				"webworker.importscripts",
				"webworker.iterable"
			],
			"include": include
		}
		if exclude:
			template["exclude"] += exclude
		declarations = resolve_declarations()
		if declarations:
			template["files"] = declarations
		return template

	def flush_build_target_tsconfig(self, target: TscBuildTarget):
		output_filename = os.path.basename(target.output_path)
		if isinstance(target.source, DirectorySource):
			include = target.source.includes.include
			exclude = target.source.includes.exclude
		else:
			include = [target.source.source_path]
			exclude = None

		for composite in [True, False]:
			tsconfig_path = os.path.join(self.tsc_path, target.composite_path if composite else target.incremental_path)
			tsconfig = self.create_tsconfig_contents(include, exclude, outFile=output_filename, composite=composite)
			flush_json_if_changed(tsconfig_path, tsconfig)

	def flush_composite_tsconfig(self, targets: List[TscBuildTarget]):
		composite_files = []
		for target in targets:
			composite_files.append({
				"path": os.path.relpath(target.composite_path, self.tsc_path)
			})
		tsconfig = {
			"compilerOptions": {
				"composite": True
			},
			"references": composite_files
		}
		flush_json_if_changed(self.composite_path, tsconfig)

	def search_changed_build_targets(self, targets: List[TscBuildTarget]) -> List[TscBuildTarget]:
		changed_targets = []
		for target in targets:
			has_source_changes = GLOBALS.BUILD_STORAGE.is_path_changed(target.source.source_path)
			has_tsconfig_changes = GLOBALS.BUILD_STORAGE.is_path_changed(target.incremental_path)
			if has_source_changes or has_tsconfig_changes or not os.path.isfile(target.output_path):
				changed_targets.append(target)
		return changed_targets

	def transpile_with_tsc(self, *args: str) -> int:
		from .script_setup import request_typescript
		tsc = request_typescript()
		if not tsc:
			raise RuntimeError("A tsc is required to build this source, make sure it is present before transpiling.")

		command = [tsc, *args]
		if not PROPERTIES.get_value("release"):
			# Do NOT resolve down-level declaration, like 'android.d.ts' if it is not included
			command.append("--noResolve")
			# Do NOT check declarations to resolve conflicts and something else due to --noResolve
			command.append("--skipLibCheck")

		return subprocess.call(command, shell=platform.system() == "Windows")

	def transpile_incremental(self, target: TscBuildTarget) -> int:
		return self.transpile_with_tsc("--project", target.incremental_path)

	def transpile_composite(self) -> int:
		return self.transpile_with_tsc("--build", self.composite_path)

	def requires_composite_build(self, targets: List[TscBuildTarget], changed_targets: List[TscBuildTarget]) -> bool:
		composite_enabled = GLOBALS.MAKE_CONFIG.get("project.composite")
		if composite_enabled is not None and composite_enabled != "auto":
			return composite_enabled is True
		return len(changed_targets) > 1

	def transpile(self, repository: ScriptRepository) -> int:
		ensure_directory(self.tsc_path)
		targets = self.prepare_build_targets(repository)
		for target in targets:
			self.flush_build_target_tsconfig(target)
		self.flush_composite_tsconfig(targets)

		changed_targets = self.search_changed_build_targets(targets)
		if not changed_targets:
			return 0
		overall_result = 0
		if self.requires_composite_build(targets, changed_targets):
			overall_result = self.transpile_composite()
		else:
			for target in changed_targets:
				overall_result += self.transpile_incremental(target)
		return overall_result

class BabelTranspiler(ScriptTranspiler):
	def __init__(self) -> None:
		super().__init__()
		self.babel_path = GLOBALS.MAKE_CONFIG.get_build_path("script", "babel")

	def transpile_with_babel(self, *args: str) -> int:
		from .babel_setup import request_babel
		babel = request_babel()
		if not babel:
			raise RuntimeError("A babel is required to build this source, make sure it is present before transpiling.")

		command = [babel, *args, "--no-babelrc"]
		return subprocess.call(command, shell=platform.system() == "Windows")

	def transpile(self, repository: ScriptRepository) -> int:
		ensure_directory(self.babel_path)
		return 0
