import json
import os.path
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import TYPE_CHECKING, Iterable, List, Optional

from .context import GLOBALS
from .hglob import glob
from .utils import (copy_file, ensure_directory, ensure_file,
                    relativize_or_hash_path)

if TYPE_CHECKING:
	from .includes import Includes


@dataclass
class ScriptSource:
	source_path: str
	destination_path: str
	transpiler: str

@dataclass
class DirectorySource(ScriptSource):
	includes: 'Includes'

###
# Project configs now should be readen before flushing, compared via
# object comparison (to drop comments, whitespace, etc.) and tsconfigs
# in projects itself should contain only specific source options.

# <project>
	# dev
		# .includes
		# header.ts
		# tsconfig.json (autogenerated)
	# launcher.ts
	# preloader.ts
	# tsconfig.json (autogenerated)

# Build directory configs will contain following structure:
# - Composite configs contains `composite: true` in directories and
# referenced directly in root file which will be used for release builds.
# - Incremental configs does NOT contains it, only `incremental: true`,
# no references, only direct file includes, directories built separately.
# * No separate reference/incremental tsconfig to include launcher.ts or
# preloader.ts, they will be included direcly via `include` property.

# <build_directory>
	# tsc (output directory + tsconfigs)
		# dev
			# composite-tsconfig.json
			# incremental-tsconfig.json
		# composite-tsconfig.json
		# incremental-tsconfig.json
	# babel (pretty same, but with babel configs)
	# sources (probably has been deprecated, concat transpiler outputs file directly)
###

class ScriptRepository:
	files: List[ScriptSource] = []
	directories: List[DirectorySource] = []

	def include_file(self, source_path: str, destination_path: str, transpiler: str):
		self.files.append(ScriptSource(source_path, destination_path, transpiler))

	def include_directory(self, includes: 'Includes', destination_path: str, transpiler: str):
		self.directories.append(DirectorySource(includes.directory, destination_path, transpiler, includes))

	def iterate_files(self, transpiler: Optional[str] = None) -> Iterable[ScriptSource]:
		for file in self.files:
			if not transpiler or transpiler == file.transpiler:
				yield file

	def iterate_directories(self, transpiler: Optional[str] = None) -> Iterable[DirectorySource]:
		for directory in self.directories:
			if not transpiler or transpiler == directory.transpiler:
				yield directory

	def iterate(self, transpiler: Optional[str] = None) -> Iterable[ScriptSource]:
		yield from self.iterate_files(transpiler)
		yield from self.iterate_directories(transpiler)

def resolve_declarations() -> List[str]:
	includes = GLOBALS.MAKE_CONFIG.get_value("declarations", ["declarations"])
	declarations = []
	for filepath in [
		GLOBALS.MAKE_CONFIG.get_path(include) for include in includes
	]:
		if not os.path.exists(filepath):
			continue
		if os.path.isdir(filepath):
			filepath = os.path.join(filepath, "**", "*.d.ts")
		declarations.extend(glob(filepath, recursive=True))

	toolchain_declarations = GLOBALS.TOOLCHAIN_CONFIG.get_relative_path("declarations")
	if not os.path.isdir(toolchain_declarations):
		from .output_directory import get_config_directory
		toolchain_declarations = os.path.join(get_config_directory(), "declarations")
	if os.path.isdir(toolchain_declarations):
		declarations.extend(glob(os.path.join(toolchain_declarations, "**", "*.d.ts"), recursive=True))

	return list(set(declarations))

class ScriptTranspiler(ABC):
	@abstractmethod
	def transpile(self, repository: ScriptRepository) -> int:
		...

class ConcatTranspiler(ScriptTranspiler):
	def transpile(self, repository: ScriptRepository) -> int:
		overall_result = 0

		for file in repository.iterate_files("concat"):
			if GLOBALS.BUILD_STORAGE.is_path_changed(file.source_path) or not os.path.isfile(file.destination_path):
				copy_file(file.source_path, file.destination_path)

		for directory in repository.iterate_directories("concat"):
			if directory.includes.compute(directory.destination_path, "javascript"):
				overall_result += directory.includes.build_source(directory.destination_path, "javascript")

		return overall_result

@dataclass
class TscBuildTarget:
	source: ScriptSource
	composite_path: str
	incremental_path: str

class TscTranspiler(ScriptTranspiler):
	def create_tsconfig_contents(self, include: List[str], exclude: Optional[List[str]] = None, **options) -> dict:
		template = {
			"compilerOptions": {
				# TypeScript Compiler 6+ Changes
				"strict": False,
				"ignoreDeprecations": "6.0",
				# Overrideable configurations and internal options
				**GLOBALS.TSCONFIG_TOOLCHAIN,
				**options
			},
			"exclude": [
				"dom",
				"dom.iterable",
				"es2015.iterable",
				"scripthost",
				"webworker",
				"webworker.importscripts",
				"webworker.iterable"
			],
			"include": include
		}

		if exclude:
			template["exclude"] += exclude
		declarations = resolve_declarations()
		if len(declarations) > 0:
			template["files"] = declarations
		return template

	def flush_files_config(self, tsconfig_path: str, files: List[ScriptSource], **options):
		include = [file.source_path for file in files]
		tsconfig = self.create_tsconfig_contents(include, None, **options, outDir=".")

		ensure_file(tsconfig_path)
		with open(tsconfig_path, "w", encoding="utf-8") as file:
			file.write(json.dumps(tsconfig, indent="\t", ensure_ascii=False) + "\n")

	def flush_directory_config(self, tsconfig_path: str, directory: DirectorySource, **options):
		output_filename = os.path.basename(directory.destination_path)
		tsconfig = self.create_tsconfig_contents(directory.includes.include, directory.includes.exclude, **options, outFile=output_filename)

		ensure_file(tsconfig_path)
		with open(tsconfig_path, "w", encoding="utf-8") as file:
			file.write(json.dumps(tsconfig, indent="\t", ensure_ascii=False) + "\n")

	def prepare_build_targets(self, repository: ScriptRepository) -> List[TscBuildTarget]:
		tsc_path = GLOBALS.MAKE_CONFIG.get_build_path("tsc")
		ensure_directory(tsc_path)
		build_targets: List[TscBuildTarget] = []

		files = list(repository.iterate_files("tsc"))
		if files:
			composite_tsconfig = os.path.join(tsc_path, "composite-files.tsconfig.json")
			self.flush_files_config(composite_tsconfig, files, composite=True)
			incremental_tsconfig = os.path.join(tsc_path, "files.tsconfig.json")
			self.flush_files_config(incremental_tsconfig, files, composite=False)
			for file in files:
				build_targets.append(TscBuildTarget(file, composite_tsconfig, incremental_tsconfig))

		directories = list(repository.iterate_directories("tsc"))
		for directory in directories:
			relative_output_path = relativize_or_hash_path(directory.source_path, GLOBALS.MAKE_CONFIG.directory)
			output_path = os.path.join(tsc_path, relative_output_path)
			ensure_directory(output_path)

			composite_tsconfig = os.path.join(output_path, "composite-directory.tsconfig.json")
			self.flush_directory_config(composite_tsconfig, directory, composite=True)
			incremental_tsconfig = os.path.join(output_path, "directory.tsconfig.json")
			self.flush_directory_config(incremental_tsconfig, directory, composite=False)

			build_targets.append(TscBuildTarget(directory, composite_tsconfig, incremental_tsconfig))

		return build_targets

	def transpile(self, repository: ScriptRepository) -> int:
		overall_result = 0
		targets = self.prepare_build_targets(repository)
		return overall_result
